export { MovieList } from "./MovieList"
export { Search } from "./Search"
export { PageNotFound } from "./PageNotFound"
export { MovieDetails } from "./MovieDetails"
export { AllMovies } from "./AllMovies"
export {Watchlist} from "./Watchlist"
export {UserProfile} from "./UserProfile"
export {Theatre} from "./Theatre"